/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.payouth.apiserver.api.interfaces;

import org.payouth.apiserver.model.Candidate;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-09-22T10:25:30.542949600-04:00[America/New_York]")
@Validated
@Tag(name = "candidate", description = "Condidate profile")
public interface CandidateApi {

    /**
     * POST /candidates : Create Candidate
     * Create a new Candidate.
     *
     * @param candidate Created Candidate object (optional)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "createCandidate",
        summary = "Create Candidate",
        description = "Create a new Candidate.",
        tags = { "candidate" },
        responses = {
            @ApiResponse(responseCode = "default", description = "successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Candidate.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/candidates",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Candidate> createCandidate(
        @Parameter(name = "Candidate", description = "Created Candidate object") @Valid @RequestBody(required = false) Candidate candidate
    );


    /**
     * GET /candidates/{fistName}/{lastName} : Returns a specific candidate
     *
     * @param fistName The first name of the candidate (required)
     * @param lastName The last name of the candidate (required)
     * @return successful operation (status code 200)
     *         or Invalid candidate supplied (status code 400)
     *         or Candidate not found (status code 404)
     */
    @Operation(
        operationId = "getCandidateByNameNadLatName",
        summary = "Returns a specific candidate",
        tags = { "candidate" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Candidate.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid candidate supplied"),
            @ApiResponse(responseCode = "404", description = "Candidate not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/candidates/{fistName}/{lastName}",
        produces = { "application/json" }
    )
    ResponseEntity<Candidate> getCandidateByNameNadLatName(
        @Parameter(name = "fistName", description = "The first name of the candidate", required = true, in = ParameterIn.PATH) @PathVariable("fistName") String fistName,
        @Parameter(name = "lastName", description = "The last name of the candidate", required = true, in = ParameterIn.PATH) @PathVariable("lastName") String lastName
    );


    /**
     * GET /candidates : Returns list of elections
     *
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "getCandidates",
        summary = "Returns list of elections",
        tags = { "candidate" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Candidate.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/candidates",
        produces = { "application/json" }
    )
    ResponseEntity<List<Candidate>> getCandidates(
        
    );


    /**
     * PUT /candidates/{fistName}/{lastName} : update candidate
     * update a new candidate.
     *
     * @param fistName The first name of the candidate (required)
     * @param lastName The last name of the candidate (required)
     * @param candidate update candidate object (optional)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "updateCandidate",
        summary = "update candidate",
        description = "update a new candidate.",
        tags = { "candidate" },
        responses = {
            @ApiResponse(responseCode = "default", description = "successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Candidate.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/candidates/{fistName}/{lastName}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Candidate> updateCandidate(
        @Parameter(name = "fistName", description = "The first name of the candidate", required = true, in = ParameterIn.PATH) @PathVariable("fistName") String fistName,
        @Parameter(name = "lastName", description = "The last name of the candidate", required = true, in = ParameterIn.PATH) @PathVariable("lastName") String lastName,
        @Parameter(name = "Candidate", description = "update candidate object") @Valid @RequestBody(required = false) Candidate candidate
    );

}
