/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.payouth.apiserver.api.interfaces;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.payouth.apiserver.model.Comment;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.annotation.Generated;
import javax.validation.Valid;
import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-09-22T04:57:50.978439+01:00[Europe/London]")
@Validated
@Tag(name = "comments", description = "Add/View comments")
public interface CommentsApi {

    /**
     * GET /elections/{electionId}/comments : Get all comment for Election
     *
     * @param electionId Election ID (required)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "getAllCommentsInElection",
        summary = "Get all comment for Election",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Comment.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/elections/{electionId}/comments",
        produces = { "application/json" }
    )
    ResponseEntity<List<Comment>> getAllCommentsInElection(
        @Parameter(name = "electionId", description = "Election ID", required = true, in = ParameterIn.PATH) @PathVariable("electionId") String electionId
    );


    /**
     * GET /elections/{electionId}/stages/{stageId}/comments : Get all comment for Stage
     *
     * @param electionId Election ID (required)
     * @param stageId Election ID (required)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "getAllCommentsInStage",
        summary = "Get all comment for Stage",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Comment.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/elections/{electionId}/stages/{stageId}/comments",
        produces = { "application/json" }
    )
    ResponseEntity<List<Comment>> getAllCommentsInStage(
        @Parameter(name = "electionId", description = "Election ID", required = true, in = ParameterIn.PATH) @PathVariable("electionId") String electionId,
        @Parameter(name = "stageId", description = "Election ID", required = true, in = ParameterIn.PATH) @PathVariable("stageId") String stageId
    );


    /**
     * POST /elections/{electionId}/comments : Add a new comment for Election
     *
     * @param electionId Election ID (required)
     * @param comment Comment to be added (optional)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "postCommentInElection",
        summary = "Add a new comment for Election",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Comment.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/elections/{electionId}/comments",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Comment> postCommentInElection(
        @Parameter(name = "electionId", description = "Election ID", required = true, in = ParameterIn.PATH) @PathVariable("electionId") String electionId,
        @Parameter(name = "Comment", description = "Comment to be added") @Valid @RequestBody(required = false) Comment comment
    );


    /**
     * POST /elections/{electionId}/stages/{stageId}/comments : Add a new comment for Stage
     *
     * @param electionId Election ID (required)
     * @param stageId Election ID (required)
     * @param comment Comment to be added (optional)
     * @return successful operation (status code 200)
     */
    @Operation(
        operationId = "postCommentInStage",
        summary = "Add a new comment for Stage",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Comment.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/elections/{electionId}/stages/{stageId}/comments",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Comment> postCommentInStage(
        @Parameter(name = "electionId", description = "Election ID", required = true, in = ParameterIn.PATH) @PathVariable("electionId") String electionId,
        @Parameter(name = "stageId", description = "Election ID", required = true, in = ParameterIn.PATH) @PathVariable("stageId") String stageId,
        @Parameter(name = "Comment", description = "Comment to be added") @Valid @RequestBody(required = false) Comment comment
    );

}
